package graphql;

// *** FIXED IMPORTS ***
// Use the JPA Entity class for all operations
import com.TAN.LAB9.Entity.Product;
// import com.TAN.LAB7.model.Product; // <-- DELETED
// *********************

import com.TAN.LAB9.service.ProductService;
import org.springframework.graphql.data.method.annotation.Argument;
import org.springframework.graphql.data.method.annotation.MutationMapping;
import org.springframework.graphql.data.method.annotation.QueryMapping;
import org.springframework.stereotype.Controller;

import java.util.List;
import java.util.Optional;

@Controller
public class ProductGraphQLController {

    private final ProductService productService;

    public ProductGraphQLController(ProductService productService) {
        this.productService = productService;
    }

    @QueryMapping
    public List<Product> getAllProducts() {
        return productService.getAllProducts();
    }

    @QueryMapping
    public Optional<Product> getProductById(@Argument Long id) {
        return productService.getProductById(id);
    }

    @QueryMapping
    public List<Product> searchProducts(@Argument String name) {
        return productService.searchProductsByName(name);
    }

    @QueryMapping
    public Integer getProductsCount() {
        return productService.getAllProducts().size();
    }

    @MutationMapping
    public Product createProduct(@Argument String name, @Argument Double price) {
        // FIX: Use the required arguments constructor (Product(name, price))
        // generated by Lombok's @RequiredArgsConstructor on the Entity.
        Product product = new Product();
        return productService.createProduct(product);
    }

    @MutationMapping
    public Optional<Product> updateProduct(@Argument Long id, @Argument String name, @Argument Double price) {
        // FIX: Use the required arguments constructor for the details object.
        Product productDetails = new Product();
        // Note: The service layer will only use these values to update the existing entity.
        return productService.updateProduct(id, productDetails);
    }

    @MutationMapping
    public Boolean deleteProduct(@Argument Long id) {
        return productService.deleteProduct(id);
    }

    @MutationMapping
    public Product addProduct(@Argument ProductInput productInput) {
        Product product = new Product();
        return productService.createProduct(product);
    }

    public record ProductInput(String name, Double price) {}
}
